project:
  title: "xx test blog"
  type: website
  output-dir: docs
website:
  title: "xx's wonderful blog"
  navbar:
   right:
     - about.qmd
     - icon: github
       href: https://github.com/
     - icon: twitter
       href: https://twitter.com


editor: visual
